# Generated by Django 5.1.5 on 2025-01-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(help_text='Введите наименование организации покупателя', max_length=100, verbose_name='Наименование')),
                ('inn', models.CharField(help_text='Введите ИНН организации покупателя', max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(help_text='Введите КПП организации покупателя', max_length=50, verbose_name='КПП')),
                ('ogrn', models.CharField(help_text='Введите ОГРН организации покупателя', max_length=50, verbose_name='ОГРН')),
                ('address', models.TextField(help_text='Введите адрес организации покупателя', verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Введите телефон организации покупателя', max_length=50, verbose_name='Телефон')),
                ('code_company', models.CharField(help_text='Пример: Клиент, Заказчик, Покупатель', max_length=50, verbose_name='Условное наименование организации покупателя')),
            ],
        ),
        migrations.CreateModel(
            name='InformationOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(help_text='Введите наименование организации', max_length=100, verbose_name='Наименование')),
                ('inn', models.CharField(help_text='Введите ИНН организации', max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(help_text='Введите КПП организации', max_length=50, verbose_name='КПП')),
                ('ogrn', models.CharField(help_text='Введите ОГРН организации', max_length=50, verbose_name='ОГРН')),
                ('address', models.TextField(help_text='Введите адрес организации', verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Введите телефон организации', max_length=50, verbose_name='Телефон')),
                ('fax', models.CharField(help_text='Введите факс организации', max_length=50, verbose_name='Факс')),
                ('position_at_work', models.CharField(help_text='Введите должность руководителя организации', max_length=50, verbose_name='Должность руководителя')),
                ('supervisor', models.CharField(help_text='Введите ФИО руководителя организации', max_length=100, verbose_name='Руководитель')),
                ('accountant', models.CharField(help_text='Введите ФИО бухгалтера организации', max_length=100, verbose_name='Бухгалтер')),
                ('code_company', models.CharField(help_text='Пример: Поставщик, Исполнитель, Продавец', max_length=50, verbose_name='Условное наименование организации')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите наименование продукта', verbose_name='Наименование')),
                ('unit_of_measurement', models.CharField(help_text='Введите единицу измерения', max_length=10, verbose_name='Единица измерения')),
                ('quantity', models.IntegerField(help_text='Введите количество товара', verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=6, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Введите скидку на товар', max_digits=6, verbose_name='Скидка')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetailsBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(help_text='Введите БИК банка', max_length=100, verbose_name='БИК')),
                ('naming', models.CharField(help_text='Введите наименование банка', max_length=100, verbose_name='Наименование')),
                ('location', models.TextField(help_text='Введите местонахождение банка', verbose_name='Местонахождение')),
                ('correspondent_account', models.CharField(help_text='Введите № корреспондентского счёта банка', max_length=100, verbose_name='Корреспондентский счёт')),
                ('current_account', models.CharField(help_text='Введите № расчетного счёта банка', max_length=100, verbose_name='Расчетный счёт')),
                ('organization', models.ForeignKey(help_text='Выберите организацию покупателя', on_delete=django.db.models.deletion.CASCADE, to='invoice.buyer', verbose_name='Организация покупателя')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetailsOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(help_text='Введите БИК банка', max_length=100, verbose_name='БИК')),
                ('naming', models.CharField(help_text='Введите наименование банка', max_length=100, verbose_name='Наименование')),
                ('location', models.TextField(help_text='Введите местонахождение банка', verbose_name='Местонахождение')),
                ('correspondent_account', models.CharField(help_text='Введите № корреспондентского счёта банка', max_length=100, verbose_name='Корреспондентский счёт')),
                ('current_account', models.CharField(help_text='Введите № расчетного счёта банка', max_length=100, verbose_name='Расчетный счёт')),
                ('organization', models.ForeignKey(help_text='Выберите организацию', on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('purpose_of_payment', models.CharField(max_length=150, verbose_name='Назначение платежа')),
                ('payment_for', models.CharField(max_length=150, verbose_name='Оплата за')),
                ('agreement', models.CharField(max_length=150, verbose_name='Договор')),
                ('bank_counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.bankdetailsbuyer', verbose_name='Банк контрагента')),
                ('bank_organization', models.ForeignKey(help_text='Выберите банк организации', on_delete=django.db.models.deletion.CASCADE, to='invoice.bankdetailsorganization', verbose_name='Банк организации')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_consignee', to='invoice.buyer', verbose_name='Грузополучатель')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_counterparty', to='invoice.buyer', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('table_product', models.ManyToManyField(blank=True, to='invoice.invoicedocumenttable', verbose_name='Таблица товаров')),
            ],
        ),
    ]
