# Generated by Django 5.1.5 on 2025-01-30 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtdDocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='Введите код товара / услуг', max_length=50, verbose_name='Код товара')),
                ('name', models.TextField(help_text='Введите наименование продукта', verbose_name='Наименование')),
                ('product_type_code', models.CharField(help_text='Введите код вида товара', max_length=50, verbose_name='Код вида товара')),
                ('unit_of_measurement', models.CharField(help_text='Введите единицу измерения', max_length=10, verbose_name='Единица измерения')),
                ('excise', models.CharField(help_text='Введите акциз', max_length=50, verbose_name='Акциз')),
                ('quantity', models.IntegerField(help_text='Введите количество товара', verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=6, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма')),
                ('country', models.CharField(help_text='Введите страну', max_length=50, verbose_name='Страна')),
                ('number_GTD', models.TextField(help_text='Введите № ГТД', verbose_name='№ ГТД')),
            ],
        ),
        migrations.CreateModel(
            name='UtdDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('payment_document', models.CharField(max_length=500, verbose_name='К платежно-расчетному документу')),
                ('shipping_document', models.CharField(max_length=500, verbose_name='Документ об отгрузке')),
                ('state_ID_contract', models.CharField(max_length=150, verbose_name='Идентификатор гос. контракта')),
                ('basis_for_transfer', models.CharField(max_length=150, verbose_name='Основание передачи')),
                ('data_transportation', models.CharField(max_length=150, verbose_name='Данные о транспортировке и грузе')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки')),
                ('date_of_receipt', models.DateField(verbose_name='Дата получения')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_consignee_utd', to='invoice.buyer', verbose_name='Грузополучатель')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_counterparty_utd', to='invoice.buyer', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_shipper_utd', to='invoice.buyer', verbose_name='Грузоотправитель')),
                ('table_product', models.ManyToManyField(to='invoice.utddocumenttable', verbose_name='Таблица товаров')),
            ],
        ),
    ]
