# Generated by Django 5.1.5 on 2025-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_utddocumenttable_utddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationorganization',
            name='stamp',
            field=models.ImageField(blank=True, upload_to='stamps'),
        ),
    ]
