# Generated by Django 5.1.5 on 2025-02-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_informationorganization_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatInvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('payment_document', models.CharField(max_length=500, verbose_name='К платежно-расчетному документу')),
                ('shipping_document', models.CharField(max_length=500, verbose_name='Документ об отгрузке')),
                ('state_ID_contract', models.CharField(max_length=150, verbose_name='Идентификатор гос. контракта')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_consignee_vat', to='invoice.buyer', verbose_name='Грузополучатель')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_counterparty_vat', to='invoice.buyer', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_shipper_vat', to='invoice.buyer', verbose_name='Грузоотправитель')),
                ('table_product', models.ManyToManyField(to='invoice.utddocumenttable', verbose_name='Таблица товаров')),
            ],
        ),
    ]
