# Generated by Django 5.1.5 on 2025-02-04 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_ks2documenttable_ks2document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informationorganization',
            name='user',
            field=models.ForeignKey(default=1, help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Акт о приемке работ КС-2 №'),
        ),
    ]
