# Generated by Django 5.1.5 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_invoicedocumenttable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialofferdocumenttable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='commercialofferdocumenttable',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ks2documenttable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='ks2documenttable',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='packinglistdocumenttable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='packinglistdocumenttable',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='utddocumenttable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='utddocumenttable',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=12, verbose_name='Цена'),
        ),
    ]
