# Generated by Django 5.1.5 on 2025-02-04 14:20

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_informationorganization_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationorganization',
            name='kpp',
            field=models.CharField(help_text='Введите КПП организации', max_length=50, validators=[invoice.models.validate_kpp], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='ogrn',
            field=models.CharField(help_text='Введите ОГРН организации', max_length=50, validators=[invoice.models.validate_ogrn], verbose_name='ОГРН'),
        ),
    ]
