# Generated by Django 5.1.5 on 2025-02-04 17:09

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_bankdetailsorganization_bic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailsbuyer',
            name='bic',
            field=models.CharField(help_text='Введите БИК банка', max_length=100, validators=[invoice.models.validate_bic], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bankdetailsbuyer',
            name='correspondent_account',
            field=models.CharField(help_text='Введите № корреспондентского счёта банка', max_length=100, validators=[invoice.models.validate_correspondent_account], verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='bankdetailsbuyer',
            name='current_account',
            field=models.CharField(help_text='Введите № расчетного счёта банка', max_length=100, validators=[invoice.models.validate_current_account], verbose_name='Расчетный счёт'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='inn',
            field=models.CharField(help_text='Введите ИНН организации покупателя', max_length=50, validators=[invoice.models.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='kpp',
            field=models.CharField(help_text='Введите КПП организации покупателя', max_length=50, validators=[invoice.models.validate_kpp], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='ogrn',
            field=models.CharField(help_text='Введите ОГРН организации покупателя', max_length=50, validators=[invoice.models.validate_ogrn], verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(help_text='Введите телефон организации покупателя', max_length=50, validators=[invoice.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
