# Generated by Django 5.1.5 on 2025-02-04 17:16

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_alter_bankdetailsbuyer_bic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailsbuyer',
            name='current_account',
            field=models.CharField(blank=True, help_text='Введите № расчетного счёта банка', max_length=100, null=True, validators=[invoice.models.validate_current_account], verbose_name='Расчетный счёт'),
        ),
        migrations.AlterField(
            model_name='bankdetailsorganization',
            name='current_account',
            field=models.CharField(blank=True, help_text='Введите № расчетного счёта банка', max_length=100, null=True, validators=[invoice.models.validate_current_account], verbose_name='Расчетный счёт'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='code_company',
            field=models.CharField(blank=True, help_text='Пример: Клиент, Заказчик, Покупатель', max_length=50, null=True, verbose_name='Условное наименование организации покупателя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефон организации покупателя', max_length=50, null=True, validators=[invoice.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='accountant',
            field=models.CharField(blank=True, help_text='Введите ФИО бухгалтера организации', max_length=100, null=True, verbose_name='Бухгалтер'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='code_company',
            field=models.CharField(blank=True, help_text='Пример: Поставщик, Исполнитель, Продавец', max_length=50, null=True, verbose_name='Условное наименование организации'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='fax',
            field=models.CharField(blank=True, help_text='Введите факс организации', max_length=50, null=True, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефон организации', max_length=50, null=True, validators=[invoice.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
