# Generated by Django 5.1.5 on 2025-02-05 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_bankdetailsbuyer_current_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ks3DocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите наименование работ, затрат', verbose_name='Наименование')),
                ('code', models.CharField(help_text='Введите код', max_length=50, verbose_name='Код')),
                ('quantity', models.IntegerField(help_text='Введите количество товара', verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=12, verbose_name='Цена')),
                ('price_from_construction', models.DecimalField(decimal_places=2, help_text='Введите стоимость', max_digits=12, verbose_name='Стоимость с начала проведения работ')),
                ('price_from_year', models.DecimalField(decimal_places=2, help_text='Введите стоимость', max_digits=12, verbose_name='Стоимость с начала года')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Ks3Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Справка КС-3 №')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('name_construction', models.CharField(max_length=250, verbose_name='Наименование стройки')),
                ('address_construction', models.CharField(max_length=150, verbose_name='Адрес стройки')),
                ('number_agreement', models.CharField(max_length=150, verbose_name='Номер договора подряда')),
                ('date_agreement', models.DateField(verbose_name='Дата договора подряда')),
                ('period_from', models.DateField(verbose_name='Отчетный период с')),
                ('period_by', models.DateField(verbose_name='Отчетный период по')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_counterparty_ks3', to='invoice.buyer', verbose_name='Контрагент')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_investor_ks3', to='invoice.buyer', verbose_name='Инвестор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('table_product', models.ManyToManyField(to='invoice.ks3documenttable', verbose_name='Таблица товаров')),
            ],
        ),
    ]
