# Generated by Django 5.1.5 on 2025-02-05 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_actservicedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerAttorneyDocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите наименование продукта', verbose_name='Наименование')),
                ('unit_of_measurement', models.CharField(help_text='Введите единицу измерения', max_length=10, verbose_name='Единица измерения')),
                ('quantity', models.IntegerField(help_text='Введите количество товара', verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='PowerAttorneyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Доверенность №')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('validity_period', models.DateField(verbose_name='Срок действия, до')),
                ('to_receive_from', models.CharField(max_length=150, verbose_name='На получение от')),
                ('according_document', models.CharField(max_length=150, verbose_name='По документу')),
                ('person_power', models.CharField(help_text='Должность, Ф.И.О. полн. в дат. падеже', max_length=250, verbose_name='Лицо, получившее доверенность')),
                ('passport_series', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(max_length=150, verbose_name='Кем выдан')),
                ('date_issue', models.DateField(verbose_name='Дата выдачи')),
                ('bank_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.bankdetailsorganization', verbose_name='Банк организации')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('table_product', models.ManyToManyField(to='invoice.powerattorneydocumenttable', verbose_name='Таблица товаров')),
            ],
        ),
    ]
