# Generated by Django 5.1.5 on 2025-02-05 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_powerattorneydocumenttable_powerattorneydocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceiptDocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(help_text='Введите артикул', max_length=100, verbose_name='Артикул')),
                ('name', models.TextField(help_text='Введите наименование продукта', verbose_name='Наименование')),
                ('unit_of_measurement', models.CharField(help_text='Введите единицу измерения', max_length=10, verbose_name='Единица измерения')),
                ('quantity', models.IntegerField(help_text='Введите количество товара', verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=12, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Чек №')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('table_product', models.ManyToManyField(to='invoice.salesreceiptdocumenttable', verbose_name='Таблица товаров')),
            ],
        ),
    ]
