# Generated by Django 5.1.5 on 2025-02-06 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_salesreceiptdocumenttable_salesreceiptdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PkoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Приходный кассовый ордер №')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('payer', models.CharField(max_length=250, verbose_name='Информация о плательщике')),
                ('account_debit', models.CharField(max_length=150, verbose_name='Счет по дебету')),
                ('account_loan', models.CharField(max_length=150, verbose_name='Счет по кредиту')),
                ('summa', models.CharField(max_length=150, verbose_name='Сумма')),
                ('base', models.CharField(help_text='Например: Расходная накладная № 123 от 17.12.2016', max_length=250, verbose_name='Основание')),
                ('annex', models.CharField(max_length=250, verbose_name='Приложение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
