# Generated by Django 5.1.5 on 2025-02-06 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_pkodocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actservicedocument',
            options={'verbose_name': 'Акт оказания услуг', 'verbose_name_plural': 'Акт оказания услуг'},
        ),
        migrations.AlterModelOptions(
            name='bankdetailsbuyer',
            options={'verbose_name': 'Банк контрагента', 'verbose_name_plural': 'Банк контрагента'},
        ),
        migrations.AlterModelOptions(
            name='bankdetailsorganization',
            options={'verbose_name': 'Банк организации', 'verbose_name_plural': 'Банк организации'},
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагент'},
        ),
        migrations.AlterModelOptions(
            name='commercialofferdocument',
            options={'verbose_name': 'Коммерческое предложение', 'verbose_name_plural': 'Коммерческое предложение'},
        ),
        migrations.AlterModelOptions(
            name='commercialofferdocumenttable',
            options={'verbose_name': 'Таблица для документа коммерческое предложение', 'verbose_name_plural': 'Таблица для документа коммерческое предложение'},
        ),
        migrations.AlterModelOptions(
            name='informationorganization',
            options={'verbose_name': 'Информация об организации', 'verbose_name_plural': 'Информация об организации'},
        ),
        migrations.AlterModelOptions(
            name='invoicedocument',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счет'},
        ),
        migrations.AlterModelOptions(
            name='invoicedocumenttable',
            options={'verbose_name': 'Таблица для документа счет', 'verbose_name_plural': 'Таблица для документа счет'},
        ),
        migrations.AlterModelOptions(
            name='ks2document',
            options={'verbose_name': 'КС-2', 'verbose_name_plural': 'КС-2'},
        ),
        migrations.AlterModelOptions(
            name='ks2documenttable',
            options={'verbose_name': 'Таблица для документа КС-2', 'verbose_name_plural': 'Таблица для документа КС-2'},
        ),
        migrations.AlterModelOptions(
            name='ks3document',
            options={'verbose_name': 'КС-3', 'verbose_name_plural': 'КС-3'},
        ),
        migrations.AlterModelOptions(
            name='ks3documenttable',
            options={'verbose_name': 'Таблица для документа КС-3', 'verbose_name_plural': 'Таблица для документа КС-3'},
        ),
        migrations.AlterModelOptions(
            name='outlaydocument',
            options={'verbose_name': 'Смета', 'verbose_name_plural': 'Смета'},
        ),
        migrations.AlterModelOptions(
            name='packinglistdocument',
            options={'verbose_name': 'Товарная накладная', 'verbose_name_plural': 'Товарная накладная'},
        ),
        migrations.AlterModelOptions(
            name='packinglistdocumenttable',
            options={'verbose_name': 'Таблица для документа товарная накладная', 'verbose_name_plural': 'Таблица для документа товарная накладная'},
        ),
        migrations.AlterModelOptions(
            name='pkodocument',
            options={'verbose_name': 'ПКО', 'verbose_name_plural': 'ПКО'},
        ),
        migrations.AlterModelOptions(
            name='powerattorneydocument',
            options={'verbose_name': 'Доверенность', 'verbose_name_plural': 'Доверенность'},
        ),
        migrations.AlterModelOptions(
            name='powerattorneydocumenttable',
            options={'verbose_name': 'Таблица для документа доверенность', 'verbose_name_plural': 'Таблица для документа доверенность'},
        ),
        migrations.AlterModelOptions(
            name='salesreceiptdocument',
            options={'verbose_name': 'Товарный чек', 'verbose_name_plural': 'Товарный чек'},
        ),
        migrations.AlterModelOptions(
            name='salesreceiptdocumenttable',
            options={'verbose_name': 'Таблица для документа товарный чек', 'verbose_name_plural': 'Таблица для документа товарный чек'},
        ),
        migrations.AlterModelOptions(
            name='utddocument',
            options={'verbose_name': 'Упд', 'verbose_name_plural': 'Упд'},
        ),
        migrations.AlterModelOptions(
            name='utddocumenttable',
            options={'verbose_name': 'Таблица для документа упд', 'verbose_name_plural': 'Таблица для документа упд'},
        ),
        migrations.AlterModelOptions(
            name='vatinvoicedocument',
            options={'verbose_name': 'Счет-фактура', 'verbose_name_plural': 'Счет-фактура'},
        ),
        migrations.CreateModel(
            name='RkoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Приходный кассовый ордер №')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('payer', models.CharField(max_length=250, verbose_name='Информация о получателе')),
                ('passport', models.CharField(max_length=250, verbose_name='Документ, удостоверяющий личность получателя')),
                ('account_debit', models.CharField(max_length=150, verbose_name='Счет по дебету')),
                ('account_loan', models.CharField(max_length=150, verbose_name='Счет по кредиту')),
                ('summa', models.CharField(max_length=150, verbose_name='Сумма')),
                ('base', models.CharField(help_text='Например: Расходная накладная № 123 от 17.12.2016', max_length=250, verbose_name='Основание')),
                ('annex', models.CharField(max_length=250, verbose_name='Приложение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.informationorganization', verbose_name='Организация')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'РКО',
                'verbose_name_plural': 'РКО',
            },
        ),
    ]
