# Generated by Django 5.1.5 on 2025-02-06 08:39

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_alter_actservicedocument_options_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='informationorganization',
            name='kpp',
            field=models.CharField(blank=True, help_text='Для ООО', max_length=50, null=True, validators=[invoice.models.validate_kpp], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Введите ОГРН организации', max_length=50, null=True, validators=[invoice.models.validate_ogrn], verbose_name='ОГРН'),
        ),
    ]
