# Generated by Django 5.1.5 on 2025-02-07 02:11

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_alter_bankdetailsorganization_bic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailsorganization',
            name='bic',
            field=models.CharField(help_text='Введите БИК банка', max_length=100, validators=[invoice.models.validate_bic], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bankdetailsorganization',
            name='correspondent_account',
            field=models.CharField(help_text='Введите № корреспондентского счёта банка', max_length=100, validators=[invoice.models.validate_correspondent_account], verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='bankdetailsorganization',
            name='current_account',
            field=models.CharField(help_text='Введите № расчетного счёта банка', max_length=100, validators=[invoice.models.validate_current_account], verbose_name='Расчетный счёт'),
        ),
        migrations.AlterField(
            model_name='bankdetailsorganization',
            name='location',
            field=models.TextField(help_text='Введите местонахождение банка', verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='bankdetailsorganization',
            name='naming',
            field=models.CharField(help_text='Введите наименование банка', max_length=100, verbose_name='Наименование'),
        ),
    ]
