# Generated by Django 5.1.5 on 2025-02-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_alter_bankdetailsorganization_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utddocument',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='utddocument',
            name='type_document',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='date_of_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='payment_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='К платежно-расчетному документу'),
        ),
    ]
