# Generated by Django 5.1.5 on 2025-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_utddocument_currency_utddocument_type_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utddocument',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ставка НДС'),
        ),
    ]
