# Generated by Django 5.1.5 on 2025-02-07 09:48

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_utddocument_nds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utddocument',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[invoice.models.validate_nds], verbose_name='Ставка НДС'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='type_document',
            field=models.CharField(blank=True, default='Счет-фактура и передаточный документ(акт)', max_length=150, null=True, verbose_name='Тип документа'),
        ),
    ]
