# Generated by Django 5.1.5 on 2025-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_alter_utddocument_nds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utddocument',
            name='is_stamp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить печать и подпись'),
        ),
    ]
