# Generated by Django 5.1.5 on 2025-02-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_utddocument_is_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utddocument',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ставка НДС'),
        ),
    ]
