# Generated by Django 5.1.5 on 2025-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_alter_utddocument_nds'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedocument',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='is_stamp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить печать и подпись'),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ставка НДС'),
        ),
    ]
