# Generated by Django 5.1.5 on 2025-02-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_invoicedocument_currency_invoicedocument_is_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatinvoicedocument',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='vatinvoicedocument',
            name='is_stamp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить печать и подпись'),
        ),
        migrations.AddField(
            model_name='vatinvoicedocument',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ставка НДС'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Счет на оплату №'),
        ),
        migrations.AlterField(
            model_name='vatinvoicedocument',
            name='payment_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='К платежно-расчетному документу'),
        ),
    ]
