# Generated by Django 5.1.5 on 2025-02-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0040_ks2document_is_stamp_ks2document_nds'),
    ]

    operations = [
        migrations.AddField(
            model_name='ks3document',
            name='is_stamp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить печать и подпись'),
        ),
        migrations.AddField(
            model_name='ks3document',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ставка НДС'),
        ),
    ]
