# Generated by Django 5.1.5 on 2025-02-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0042_actservicedocument_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerattorneydocument',
            name='is_stamp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить печать и подпись'),
        ),
    ]
