# Generated by Django 5.1.5 on 2025-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0043_powerattorneydocument_is_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceiptdocument',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='salesreceiptdocument',
            name='is_stamp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить печать и подпись'),
        ),
    ]
