# Generated by Django 5.1.5 on 2025-02-18 07:36

import django.db.models.deletion
import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0046_rkodocument_is_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Введите ОГРН организации покупателя', max_length=50, null=True, validators=[invoice.models.validate_ogrn], verbose_name='ОГРН/ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='informationorganization',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Введите ОГРН организации', max_length=50, null=True, validators=[invoice.models.validate_ogrn], verbose_name='ОГРН/ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='basis_for_transfer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Основание передачи'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_consignee_utd', to='invoice.buyer', verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='data_transportation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Данные о транспортировке и грузе'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_shipper_utd', to='invoice.buyer', verbose_name='Грузоотправитель'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='shipping_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Документ об отгрузке'),
        ),
        migrations.AlterField(
            model_name='utddocument',
            name='state_ID_contract',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Идентификатор гос. контракта'),
        ),
    ]
