# Generated by Django 5.1.5 on 2025-02-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0047_alter_buyer_ogrn_alter_informationorganization_ogrn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utddocument',
            name='type_document',
            field=models.CharField(blank=True, default='Передаточный документ(акт)', max_length=150, null=True, verbose_name='Тип документа'),
        ),
    ]
