# Generated by Django 5.1.5 on 2025-02-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0048_alter_utddocument_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utddocument',
            name='nds',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Ставка НДС'),
        ),
    ]
