# Generated by Django 5.1.5 on 2025-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0049_alter_utddocument_nds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utddocumenttable',
            name='country',
            field=models.CharField(blank=True, help_text='Введите страну', max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='utddocumenttable',
            name='excise',
            field=models.CharField(blank=True, help_text='Введите акциз', max_length=50, null=True, verbose_name='Акциз'),
        ),
        migrations.AlterField(
            model_name='utddocumenttable',
            name='number_GTD',
            field=models.TextField(blank=True, help_text='Введите № ГТД', null=True, verbose_name='№ ГТД'),
        ),
        migrations.AlterField(
            model_name='utddocumenttable',
            name='product_code',
            field=models.CharField(blank=True, help_text='Введите код товара / услуг', max_length=50, null=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='utddocumenttable',
            name='product_type_code',
            field=models.CharField(blank=True, help_text='Введите код вида товара', max_length=50, null=True, verbose_name='Код вида товара'),
        ),
    ]
