# Generated by Django 5.1.5 on 2025-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0051_alter_utddocument_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utddocument',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
