# Generated by Django 5.1.5 on 2025-02-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0052_alter_utddocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedocument',
            name='agreement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='bank_counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.bankdetailsbuyer', verbose_name='Банк контрагента'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='bank_organization',
            field=models.ForeignKey(blank=True, help_text='Выберите банк организации', null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.bankdetailsorganization', verbose_name='Банк организации'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_consignee', to='invoice.buyer', verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='payment_for',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Оплата за'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='purpose_of_payment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назначение платежа'),
        ),
        migrations.AlterField(
            model_name='invoicedocumenttable',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите скидку на товар', max_digits=12, null=True, verbose_name='Скидка'),
        ),
    ]
