# Generated by Django 5.1.5 on 2025-02-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0053_alter_invoicedocument_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatinvoicedocument',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_consignee_vat', to='invoice.buyer', verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='vatinvoicedocument',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_shipper_vat', to='invoice.buyer', verbose_name='Грузоотправитель'),
        ),
        migrations.AlterField(
            model_name='vatinvoicedocument',
            name='shipping_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Документ об отгрузке'),
        ),
        migrations.AlterField(
            model_name='vatinvoicedocument',
            name='state_ID_contract',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Идентификатор гос. контракта'),
        ),
    ]
