# Generated by Django 5.1.5 on 2025-02-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0054_alter_vatinvoicedocument_consignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatinvoicedocument',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_shipper_vat', to='invoice.informationorganization', verbose_name='Грузоотправитель'),
        ),
    ]
