# Generated by Django 5.1.5 on 2025-02-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0055_alter_vatinvoicedocument_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialofferdocument',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='commercialofferdocument',
            name='naming',
            field=models.CharField(blank=True, help_text='Пример: на установку системы кондиционирования на 2 этаже', max_length=150, null=True, verbose_name='Наименование'),
        ),
    ]
