# Generated by Django 5.1.5 on 2025-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0056_alter_commercialofferdocument_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlaydocument',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='outlaydocument',
            name='base',
            field=models.CharField(blank=True, help_text='Пример: к Договору № 114 от 04.12.2012 г.', max_length=250, null=True, verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='outlaydocument',
            name='name_construction',
            field=models.CharField(blank=True, help_text='Пример: на установку системы кондиционирования на 2 этаже', max_length=250, null=True, verbose_name='Наименование стройки'),
        ),
        migrations.AlterField(
            model_name='outlaydocument',
            name='work_time',
            field=models.CharField(blank=True, help_text='Пример: 1 месяц с даты подписания настоящего приложения', max_length=250, null=True, verbose_name='Срок выполнения работ'),
        ),
    ]
