# Generated by Django 5.1.5 on 2025-02-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0057_alter_outlaydocument_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ks2document',
            name='address_construction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес стройки'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='date_agreement',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора подряда'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_investor', to='invoice.buyer', verbose_name='Инвестор'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='name_construction',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование стройки'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='name_object',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='number_agreement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер договора подряда'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='period_by',
            field=models.DateField(blank=True, null=True, verbose_name='Отчетный период по'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='period_from',
            field=models.DateField(blank=True, null=True, verbose_name='Отчетный период с'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='price_outlay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сметная стоимость по договору'),
        ),
        migrations.AlterField(
            model_name='ks2document',
            name='view_okdp',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вид деятельности по ОКДП'),
        ),
        migrations.AlterField(
            model_name='ks2documenttable',
            name='number_outlay',
            field=models.CharField(blank=True, help_text='Введите № по смете', max_length=50, null=True, verbose_name='№ по смете'),
        ),
        migrations.AlterField(
            model_name='ks2documenttable',
            name='number_unit',
            field=models.CharField(blank=True, help_text='Введите № ед. расц.', max_length=50, null=True, verbose_name='№ ед. расц.'),
        ),
    ]
