# Generated by Django 5.1.5 on 2025-02-23 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0058_alter_ks2document_address_construction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ks3document',
            name='address_construction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес стройки'),
        ),
        migrations.AlterField(
            model_name='ks3document',
            name='date_agreement',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора подряда'),
        ),
        migrations.AlterField(
            model_name='ks3document',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_investor_ks3', to='invoice.buyer', verbose_name='Инвестор'),
        ),
        migrations.AlterField(
            model_name='ks3document',
            name='name_construction',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование стройки'),
        ),
        migrations.AlterField(
            model_name='ks3document',
            name='number_agreement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер договора подряда'),
        ),
        migrations.AlterField(
            model_name='ks3document',
            name='period_by',
            field=models.DateField(blank=True, null=True, verbose_name='Отчетный период по'),
        ),
        migrations.AlterField(
            model_name='ks3document',
            name='period_from',
            field=models.DateField(blank=True, null=True, verbose_name='Отчетный период с'),
        ),
        migrations.AlterField(
            model_name='ks3documenttable',
            name='code',
            field=models.CharField(blank=True, help_text='Введите код', max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='ks3documenttable',
            name='price_from_construction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите стоимость', max_digits=12, null=True, verbose_name='Стоимость с начала проведения работ'),
        ),
        migrations.AlterField(
            model_name='ks3documenttable',
            name='price_from_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите стоимость', max_digits=12, null=True, verbose_name='Стоимость с начала года'),
        ),
    ]
