# Generated by Django 5.1.5 on 2025-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0059_alter_ks3document_address_construction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actservicedocument',
            name='agreement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='actservicedocument',
            name='payment_for',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Оплата за'),
        ),
    ]
