# Generated by Django 5.1.5 on 2025-02-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0060_alter_actservicedocument_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='according_document',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='По документу'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='bank_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.bankdetailsorganization', verbose_name='Банк организации'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='date_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='issued_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='person_power',
            field=models.CharField(blank=True, help_text='Должность, Ф.И.О. полн. в дат. падеже', max_length=250, null=True, verbose_name='Лицо, получившее доверенность'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='to_receive_from',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='На получение от'),
        ),
        migrations.AlterField(
            model_name='powerattorneydocument',
            name='validity_period',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия, до'),
        ),
    ]
