# Generated by Django 5.1.5 on 2025-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0061_alter_powerattorneydocument_according_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceiptdocumenttable',
            name='article_number',
            field=models.CharField(blank=True, help_text='Введите артикул', max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
