# Generated by Django 5.1.5 on 2025-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0062_alter_salesreceiptdocumenttable_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkodocument',
            name='account_debit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Счет по дебету'),
        ),
        migrations.AlterField(
            model_name='pkodocument',
            name='account_loan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Счет по кредиту'),
        ),
        migrations.AlterField(
            model_name='pkodocument',
            name='annex',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='pkodocument',
            name='base',
            field=models.CharField(blank=True, help_text='Например: Расходная накладная № 123 от 17.12.2016', max_length=250, null=True, verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='pkodocument',
            name='payer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Информация о плательщике'),
        ),
        migrations.AlterField(
            model_name='pkodocument',
            name='summa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сумма'),
        ),
    ]
