# Generated by Django 5.1.5 on 2025-04-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0069_labeltemplatedocument_alter_templatedocument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocument',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='invoice.labeltemplatedocument', verbose_name='Метки в документе'),
        ),
    ]
