# Generated by Django 5.1.5 on 2025-04-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0070_templatedocument_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementdocument',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='agreementdocument',
            name='replace_price_supply',
        ),
        migrations.RemoveField(
            model_name='agreementdocument',
            name='strength_supply',
        ),
        migrations.RemoveField(
            model_name='agreementdocument',
            name='time_supply',
        ),
        migrations.RemoveField(
            model_name='agreementdocument',
            name='transition_time',
        ),
    ]
