# Generated by Django 5.1.5 on 2025-04-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0071_remove_agreementdocument_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedocument',
            name='content',
            field=models.TextField(verbose_name='Содержание документа'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название шаблона'),
        ),
        migrations.CreateModel(
            name='ValueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение метки')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.labeltemplatedocument', verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Значение метки',
                'verbose_name_plural': 'Значения меток',
            },
        ),
        migrations.AddField(
            model_name='agreementdocument',
            name='dop_field',
            field=models.ManyToManyField(blank=True, null=True, to='invoice.valuelabel', verbose_name='Доп.поля'),
        ),
    ]
