# Generated by Django 5.1.5 on 2025-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0072_alter_templatedocument_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationdocumenttable',
            name='loan_org',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кредит (организация)'),
        ),
    ]
